using Xunit;

namespace Crawler.Tests
{
	/// <summary>
	/// Tests for the HTML-side file-type identification helpers in FileTypeClassifier:
	/// IsHtmlContentType (header signal), LooksLikeHtml (byte sniff), and ClassifyPage
	/// (the pure policy decision over the three signals). All are pure functions — no
	/// temp dir or logger setup required.
	///
	/// The orchestrator's Step_SettleExtensions (file renaming, 00→01 projection,
	/// #23 emission) is validated by the operator via a real crawl's 00/01/download
	/// diff; these tests cover the pure logic it depends on.
	/// </summary>
	public class FileTypeClassifierHtmlTests
	{
		// ── IsHtmlContentType ────────────────────────────────────────────
		// Decides whether a response body should be parsed for link extraction.
		// Used by Crawler.cs to skip PDFs / images / archives reached via <a href>.

		[Fact]
		public void IsHtmlContentType_TextHtml_ReturnsTrue()
		{
			Assert.True(FileTypeClassifier.IsHtmlContentType("text/html"));
		}

		[Fact]
		public void IsHtmlContentType_ApplicationXhtmlXml_ReturnsTrue()
		{
			Assert.True(FileTypeClassifier.IsHtmlContentType("application/xhtml+xml"));
		}

		[Fact]
		public void IsHtmlContentType_CaseInsensitive()
		{
			Assert.True(FileTypeClassifier.IsHtmlContentType("TEXT/HTML"));
			Assert.True(FileTypeClassifier.IsHtmlContentType("Text/Html"));
		}

		[Fact]
		public void IsHtmlContentType_NullOrEmpty_ReturnsFalse()
		{
			// When the server hasn't declared a type, don't assume the bytes
			// are parseable. Better to skip than to invent.
			Assert.False(FileTypeClassifier.IsHtmlContentType(null));
			Assert.False(FileTypeClassifier.IsHtmlContentType(""));
		}

		[Fact]
		public void IsHtmlContentType_KnownNonHtml_ReturnsFalse()
		{
			Assert.False(FileTypeClassifier.IsHtmlContentType("application/pdf"));
			Assert.False(FileTypeClassifier.IsHtmlContentType("image/png"));
			Assert.False(FileTypeClassifier.IsHtmlContentType("application/zip"));
			Assert.False(FileTypeClassifier.IsHtmlContentType("application/json"));
		}

		[Fact]
		public void IsHtmlContentType_TextPlain_ReturnsFalse()
		{
			// text/plain isn't HTML even though it's text. Parsing as HTML would
			// produce whatever HtmlAgilityPack invents from plain text — not useful.
			Assert.False(FileTypeClassifier.IsHtmlContentType("text/plain"));
		}

		[Fact]
		public void IsHtmlContentType_MediaTypePropertyAlreadyStripsCharset()
		{
			// HttpClient's MediaTypeHeaderValue.MediaType returns the bare type
			// without parameters, so callers never pass "text/html; charset=utf-8"
			// directly. But if a caller did, the equality check would fail —
			// which is the right outcome: pass MediaType only, not the full header.
			Assert.False(FileTypeClassifier.IsHtmlContentType("text/html; charset=utf-8"));
		}

		// ── LooksLikeHtml ───────────────────────────────────────────────────

		[Theory]
		[InlineData("<!DOCTYPE html><html><body>hi</body></html>")]
		[InlineData("<html lang=\"en\"><head></head></html>")]
		[InlineData("<head><title>x</title></head>")]
		[InlineData("<body><p>hi</p></body>")]
		[InlineData("<!doctype HTML>")]                // case-insensitive
		[InlineData("   \n\t  <!DOCTYPE html>")]       // leading whitespace tolerated
		public void LooksLikeHtml_HtmlOpeners_ReturnsTrue(string content)
		{
			var bytes = System.Text.Encoding.UTF8.GetBytes(content);
			Assert.True(FileTypeClassifier.LooksLikeHtml(bytes));
		}

		[Fact]
		public void LooksLikeHtml_LeadingErrorBlockBeforeDoctype_StillDetected()
		{
			// Regression: a real page may emit a server-side error/notice block before
			// the doctype. The sniff must scan the whole head, not just the start.
			var content =
				"<div class=\"block workflow_error\"><div class=\"bline\">Es ist ein Problem "
				+ "aufgetreten.</div></div>\n<!DOCTYPE html>\n<html lang=\"en\"><head>"
				+ "<title>Start page</title></head></html>";
			var bytes = System.Text.Encoding.UTF8.GetBytes(content);
			Assert.True(FileTypeClassifier.LooksLikeHtml(bytes));
		}

		[Fact]
		public void LooksLikeHtml_MetaTagAlone_NotEnough()
		{
			// <meta> alone is too weak a signal for an anywhere-in-head match and is
			// intentionally not treated as an HTML opener.
			var bytes = System.Text.Encoding.UTF8.GetBytes("<meta charset=\"utf-8\">");
			Assert.False(FileTypeClassifier.LooksLikeHtml(bytes));
		}

		[Fact]
		public void LooksLikeHtml_LeadingBom_StillDetected()
		{
			var bytes = System.Text.Encoding.UTF8.GetPreamble()
				.Concat(System.Text.Encoding.UTF8.GetBytes("<!DOCTYPE html><html></html>"))
				.ToArray();
			Assert.True(FileTypeClassifier.LooksLikeHtml(bytes));
		}

		[Fact]
		public void LooksLikeHtml_LeadingComment_ThenHtml_Detected()
		{
			var bytes = System.Text.Encoding.UTF8.GetBytes(
				"<!-- generated by CMS -->\n<!DOCTYPE html><html></html>");
			Assert.True(FileTypeClassifier.LooksLikeHtml(bytes));
		}

		[Theory]
		[InlineData("\x89PNG\r\n\x1a\n")]              // PNG magic
		[InlineData("%PDF-1.7")]                       // PDF
		[InlineData("{\"key\":\"value\"}")]            // JSON
		[InlineData("plain text with no markup")]
		[InlineData("")]                               // empty
		public void LooksLikeHtml_NonHtml_ReturnsFalse(string content)
		{
			var bytes = System.Text.Encoding.UTF8.GetBytes(content);
			Assert.False(FileTypeClassifier.LooksLikeHtml(bytes));
		}

		[Fact]
		public void LooksLikeHtml_Null_ReturnsFalse()
		{
			Assert.False(FileTypeClassifier.LooksLikeHtml(null!));
		}

		[Fact]
		public void LooksLikeHtml_BareDivFragment_NotHtml()
		{
			// A bare <div> fragment contains no strong HTML opener anywhere in the head,
			// so the sniff says not-HTML — documented behaviour (TrustContentType is the
			// escape hatch for fragment repos that serve such fragments as text/html).
			var div = System.Text.Encoding.UTF8.GetBytes("<div><p>hi</p></div>");
			Assert.False(FileTypeClassifier.LooksLikeHtml(div));
		}

		// ── ClassifyPage: agreement cases (no policy, no mismatch) ──────────

		[Theory]
		[InlineData(UnverifiedHtmlPolicy.TrustByteSniff)]
		[InlineData(UnverifiedHtmlPolicy.TrustContentType)]
		[InlineData(UnverifiedHtmlPolicy.Quarantine)]
		[InlineData(UnverifiedHtmlPolicy.AnalyseBlindly)]
		public void ClassifyPage_AllSignalsHtml_AnalyseNoMismatch_RegardlessOfPolicy(
			UnverifiedHtmlPolicy policy)
		{
			var v = FileTypeClassifier.ClassifyPage(policy, requestedExtIsHtml: true,
				headerIsHtml: true, sniffIsHtml: true);
			Assert.True(v.TreatAsHtml);
			Assert.False(v.IsMismatch);
		}

		[Theory]
		[InlineData(UnverifiedHtmlPolicy.TrustByteSniff)]
		[InlineData(UnverifiedHtmlPolicy.TrustContentType)]
		[InlineData(UnverifiedHtmlPolicy.Quarantine)]
		[InlineData(UnverifiedHtmlPolicy.AnalyseBlindly)]
		public void ClassifyPage_NoSignalsHtml_QuarantineNoMismatch_RegardlessOfPolicy(
			UnverifiedHtmlPolicy policy)
		{
			var v = FileTypeClassifier.ClassifyPage(policy, requestedExtIsHtml: false,
				headerIsHtml: false, sniffIsHtml: false);
			Assert.False(v.TreatAsHtml);
			Assert.False(v.IsMismatch);
		}

		// ── ClassifyPage: disagreement → policy decides, always a mismatch ──

		[Fact]
		public void ClassifyPage_TrustByteSniff_FollowsSniff()
		{
			// Header says HTML, sniff says not → TrustByteSniff quarantines.
			var v1 = FileTypeClassifier.ClassifyPage(UnverifiedHtmlPolicy.TrustByteSniff,
				requestedExtIsHtml: true, headerIsHtml: true, sniffIsHtml: false);
			Assert.False(v1.TreatAsHtml);
			Assert.True(v1.IsMismatch);

			// Header says not-HTML, sniff says HTML → TrustByteSniff analyses.
			var v2 = FileTypeClassifier.ClassifyPage(UnverifiedHtmlPolicy.TrustByteSniff,
				requestedExtIsHtml: false, headerIsHtml: false, sniffIsHtml: true);
			Assert.True(v2.TreatAsHtml);
			Assert.True(v2.IsMismatch);
		}

		[Fact]
		public void ClassifyPage_TrustContentType_FollowsHeader()
		{
			// Sniff says not-HTML, header says HTML → TrustContentType analyses
			// (the fragment-repo escape hatch).
			var v = FileTypeClassifier.ClassifyPage(UnverifiedHtmlPolicy.TrustContentType,
				requestedExtIsHtml: true, headerIsHtml: true, sniffIsHtml: false);
			Assert.True(v.TreatAsHtml);
			Assert.True(v.IsMismatch);
		}

		[Fact]
		public void ClassifyPage_Quarantine_NeverAnalysesAMismatch()
		{
			// Even when header and sniff both say HTML, if the requested ext disagrees
			// it is a mismatch and Quarantine refuses.
			var v = FileTypeClassifier.ClassifyPage(UnverifiedHtmlPolicy.Quarantine,
				requestedExtIsHtml: false, headerIsHtml: true, sniffIsHtml: true);
			Assert.False(v.TreatAsHtml);
			Assert.True(v.IsMismatch);
		}

		[Fact]
		public void ClassifyPage_AnalyseBlindly_AlwaysAnalysesAMismatch()
		{
			// Header and sniff both say not-HTML, but requested ext implied HTML →
			// mismatch, and AnalyseBlindly analyses anyway.
			var v = FileTypeClassifier.ClassifyPage(UnverifiedHtmlPolicy.AnalyseBlindly,
				requestedExtIsHtml: true, headerIsHtml: false, sniffIsHtml: false);
			Assert.True(v.TreatAsHtml);
			Assert.True(v.IsMismatch);
		}
	}
}
